In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv("../Data/data.csv")

In [3]:

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61692 entries, 0 to 61691
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Text        61121 non-null  object
 1   Labels      61692 non-null  int64
 2   clean_text  60814 non-null  object
 3   hashtags    61692 non-null  object
 4   mentions    61692 non-null  object
dtypes: int64(1), object(4)
memory usage: 2.4+ MB

In [4]:
data.head()

,Text,Labels,clean_text,hashtags,mentions
0,im getting on borderlands and i will murder yo...,2,im getting on borderlands and i will murder yo...,[],[]
1,I am coming to the borders and I will kill you...,2,i am coming to the borders and i will kill you...,[],[]
2,im getting on borderlands and i will kill you ...,2,im getting on borderlands and i will kill you all,[],[]
3,im coming on borderlands and i will murder you...,2,im coming on borderlands and i will murder you...,[],[]
4,im getting on borderlands 2 and i will murder ...,2,im getting on borderlands and i will murder yo...,[],[]

In [5]:
data.isna().sum()

Text          571
Labels          0
clean_text    878
hashtags        0
mentions        0
dtype: int64

In [6]:
data["Labels"].value_counts()

Labels
0    22542
2    20832
1    18318
Name: count, dtype: int64

In [7]:
!pip install contractions
!pip install spacy

Requirement already satisfied: contractions in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (0.1.73)
Requirement already satisfied: textsearch>=0.0.21 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from contractions) (0.0.24)
Requirement already satisfied: anyascii in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from textsearch>=0.0.21->contractions) (0.3.3)
Requirement already satisfied: pyahocorasick in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from textsearch>=0.0.21->contractions) (2.3.0)
Requirement already satisfied: spacy in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (0.24.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (2.2.6)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (2.33.1)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (2.12.5)
Requirement already satisfied: jinja2 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from spacy) (81.0.0)
Requirement already satisfied: packaging>=20.0 in c:\users\mohma\appdata\roaming\python\python310\site-packages (from spacy) (26.0)
Requirement already satisfied: typing_extensions<5.0,>=4.0 in c:\users\mohma\appdata\roaming\python\python310\site-packages (from confection<2.0.0,>=1.3.2->spacy) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: colorama in c:\users\mohma\appdata\roaming\python\python310\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.2.1 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.3.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.0)
Requirement already satisfied: httpx>=0.24.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\mohma\appdata\roaming\python\python310\site-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.1.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\mohma\appdata\roaming\python\python310\site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mohma\appdata\local\programs\python\python310\lib\site-packages (from jinja2->spacy) (3.0.3)

In [8]:
try:
    import contractions
except ImportError:
    import sys
    !{sys.executable} -m pip install contractions
    import contractions

# توسيع الاختصارات:
def expand_contractions(s):
    return contractions.fix(s)

# مثال
sentence = data['clean_text'][10]
print(sentence)
sentence = expand_contractions(sentence)
print(sentence)

so i spent a few hours making something for fun if you don t know i am a huge rhandlerr fan and maya is one of my favorite characters so i decided to make myself a wallpaper for my pc here is the original image versus the creation i made enjoy pic twitter com mlsi wf jg
so i spent a few hours making something for fun if you don t know i am a huge rhandlerr fan and maya is one of my favorite characters so i decided to make myself a wallpaper for my pc here is the original image versus the creation i made enjoy pic twitter com mlsi wf jg

In [9]:
data

,Text,Labels,clean_text,hashtags,mentions
0,im getting on borderlands and i will murder yo...,2,im getting on borderlands and i will murder yo...,[],[]
1,I am coming to the borders and I will kill you...,2,i am coming to the borders and i will kill you...,[],[]
2,im getting on borderlands and i will kill you ...,2,im getting on borderlands and i will kill you all,[],[]
3,im coming on borderlands and i will murder you...,2,im coming on borderlands and i will murder you...,[],[]
4,im getting on borderlands 2 and i will murder ...,2,im getting on borderlands and i will murder yo...,[],[]
...,...,...,...,...,...
61687,Just realized that the Windows partition of my...,2,just realized that the windows partition of my...,[],[]
61688,Just realized that my Mac window partition is ...,2,just realized that my mac window partition is ...,[],[]
61689,Just realized the windows partition of my Mac ...,2,just realized the windows partition of my mac ...,[],[]
61690,Just realized between the windows partition of...,2,just realized between the windows partition of...,[],[]
61691,Just like the windows partition of my Mac is l...,2,just like the windows partition of my mac is l...,[],[]

In [10]:
data["Labels"].value_counts()

Labels
0    22542
2    20832
1    18318
Name: count, dtype: int64

In [11]:
X=data['clean_text']
Y=data["Labels"]
X = X.astype(str)
print(X.dtype)
print(Y.dtype)

object
int64

In [12]:
Y

0        2
1        2
2        2
3        2
4        2
        ..
61687    2
61688    2
61689    2
61690    2
61691    2
Name: Labels, Length: 61692, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split


Xtrain, Xtemp, ytrain, ytemp = train_test_split(
    X, Y, test_size=0.2, random_state=42, stratify=Y
)


Xval, Xtest, yval, ytest = train_test_split(
    Xtemp, ytemp, test_size=0.5, random_state=42, stratify=ytemp
)

In [14]:
Xtrain.shape,Xval.shape,Xtest.shape,ytest.shape

((49353,), (6169,), (6170,), (6170,))

In [15]:
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.unique(ytrain)

weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=ytrain
)

class_weights = dict(zip(classes, weights))
print(class_weights)

{np.int64(0): np.float64(0.9122719458770032), np.int64(1): np.float64(1.1226286338201175), np.int64(2): np.float64(0.9870994839793592)}

In [16]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(Xtrain) 

X_train_seq = tokenizer.texts_to_sequences(Xtrain)
X_val_seq   = tokenizer.texts_to_sequences(Xval)
X_test_seq  = tokenizer.texts_to_sequences(Xtest)

In [17]:
X_train_seq

[[2913, 215, 59, 73, 2, 327, 389, 7, 2500, 159, 1356, 18, 8, 4012],
 [2,
  122,
  321,
  16,
  192,
  20,
  11,
  253,
  5,
  95,
  147,
  116,
  59,
  26,
  73,
  8687,
  5,
  8,
  16,
  6,
  3710,
  437,
  172,
  8,
  10,
  638,
  125,
  8688,
  511,
  8,
  8689,
  18,
  199,
  160,
  1972,
  18639],
 [52, 479, 52, 313, 38, 4013, 96, 96, 96, 96, 37, 40, 19, 14153, 116, 199],
 [6932,
  3,
  101,
  18640,
  4,
  207,
  3,
  25,
  73,
  94,
  3711,
  34,
  29,
  7,
  2,
  320,
  84,
  78,
  8,
  1925,
  24,
  166,
  17,
  194,
  494,
  9,
  52,
  34,
  8,
  10,
  1126,
  1195,
  3,
  33,
  94,
  91,
  34,
  320,
  196,
  153,
  84,
  533,
  124,
  3,
  26,
  30,
  18,
  43,
  6,
  867,
  7,
  8,
  101,
  3,
  2,
  108,
  49,
  17,
  16,
  136],
 [2437, 257, 2005, 11080, 1368, 1383, 34, 695, 133, 25, 6, 91, 328],
 [8,
  127,
  25,
  73,
  107,
  225,
  53,
  2,
  2111,
  265,
  11081,
  10,
  56,
  522,
  5,
  6,
  512,
  104,
  104,
  22,
  232,
  460,
  446,
  18641,
  14154,
  33,
  6,
  622],
 [54,
  466,
  66,
  2,
  95,
  147,
  116,
  5,
  147,
  16,
  1681,
  186,
  2,
  135,
  1150,
  8690,
  3712,
  2501,
  59,
  73,
  2502,
  14,
  6394,
  8,
  159,
  6394,
  8,
  159,
  196,
  602,
  883],
 [704,
  22,
  11082,
  1054,
  324,
  90,
  15,
  487,
  337,
  1401,
  31,
  39,
  263,
  3859,
  61,
  67,
  105,
  31,
  128,
  4178],
 [184, 35, 2, 651, 1638, 55, 619, 12, 58, 722, 125],
 [884, 241, 9, 4378],
 [1140,
  420,
  7,
  2,
  1492,
  155,
  7,
  205,
  174,
  309,
  322,
  249,
  59,
  1071,
  3713,
  1028,
  174,
  309,
  4858,
  1973,
  277,
  16518],
 [155,
  7,
  205,
  322,
  249,
  2,
  4379,
  9,
  412,
  388,
  12,
  58,
  23,
  1800,
  34,
  2,
  200,
  89,
  528,
  596,
  226,
  3,
  32,
  223,
  4,
  87,
  112,
  169,
  14,
  12,
  189,
  23,
  8691,
  8692,
  454,
  687],
 [3,
  32,
  1055,
  177,
  4,
  1186,
  4,
  2,
  95,
  147,
  116,
  10,
  6,
  928,
  7,
  181,
  28,
  4,
  207,
  2,
  89,
  179,
  18,
  23,
  91,
  8,
  204,
  5,
  789,
  30,
  307,
  314,
  35,
  2314,
  2914,
  4,
  43,
  78,
  38,
  89,
  89,
  5,
  388,
  88,
  3860,
  5,
  5505,
  1710,
  2,
  383],
 [90, 236, 503, 296, 2006, 2, 20, 45, 450, 45, 2, 2, 2821, 1828],
 [65],
 [1330,
  591,
  1029,
  66,
  107,
  296,
  245,
  1617,
  1509,
  16,
  1682,
  8,
  436,
  35,
  296,
  80,
  236,
  790,
  5,
  29,
  1030,
  7,
  3,
  31,
  136,
  34,
  8],
 [60,
  1113,
  61,
  41,
  253,
  283,
  10,
  712,
  17,
  9,
  9,
  3206,
  4,
  23,
  828,
  997,
  35,
  1225,
  6933,
  2568,
  2,
  253,
  1056,
  34,
  5163,
  480,
  11083,
  5,
  137,
  166,
  11084,
  11085,
  72,
  98,
  838,
  18642,
  5,
  5506,
  41,
  253,
  14155],
 [47,
  47,
  2744,
  891,
  7,
  268,
  330,
  10,
  106,
  5,
  713,
  110,
  1275,
  16519,
  2189,
  4,
  645,
  27,
  58,
  909,
  4,
  745,
  8,
  4598,
  822,
  149,
  159,
  822,
  19,
  159,
  2745],
 [3, 64, 6, 190, 37, 40, 19, 14156],
 [87, 51, 158, 311, 59, 8693, 5164, 4, 2, 438, 7, 158, 311, 578, 10, 616],
 [1292,
  2276,
  971,
  504,
  56,
  227,
  425,
  312,
  20,
  286,
  918,
  18643,
  14157,
  18644,
  7502,
  18645,
  16520,
  18646,
  18647],
 [49, 7, 2, 79, 3110, 10, 2, 659, 7, 236],
 [33,
  109,
  4,
  120,
  6,
  783,
  50,
  66,
  1369,
  106,
  59,
  203,
  24,
  292,
  8694,
  38,
  15,
  381,
  93,
  3,
  76,
  18,
  423,
  8,
  27,
  3,
  1257,
  72,
  25,
  2190,
  14,
  38,
  2,
  78,
  3,
  423,
  181,
  471,
  7503,
  90,
  53,
  323,
  46,
  312,
  67,
  368,
  92,
  10,
  2233,
  443,
  24,
  61],
 [84, 3861, 3862, 143, 565, 2374, 196, 616],
 [155, 7, 205, 215, 82, 6, 187, 227],
 [53,
  41,
  377,
  35,
  3,
  32,
  148,
  501,
  6,
  20,
  70,
  156,
  29,
  123,
  120,
  2,
  20,
  35,
  84],
 [12, 513, 8695, 968, 1711, 6, 23, 8696],
 [101, 652, 5, 3421, 236, 1276],
 [110,
  2,
  4859,
  2746,
  7,
  1082,
  2,
  311,
  20,
  158,
  438,
  70,
  616,
  58,
  5165,
  8697,
  21,
  919,
  2915,
  160,
  346],
 [1293, 3207, 8, 461, 59, 231, 14158],
 [500,
  361,
  1510,
  115,
  4,
  8698,
  1662,
  34,
  1114,
  2045,
  149,
  16,
  3006,
  2822,
  290,
  11,
  1570,
  2277,
  7,
  791,
  3714,
  2915,
  4014,
  8699,
  65,
  270,
  8700],
 [639,
  121,
  228,
  5,
  81,
  11086,
  1639,
  1423,
  11,
  6,
  3422,
  3423,
  4,
  1103,
  5,
  717,
  8,
  16,
  41,
  173,
  373,
  4,
  2046,
  929,
  125,
  5,
  369,
  36,
  62,
  14159,
  4,
  14160],
 [1057,
  1370,
  121,
  475,
  6934,
  1115,
  1801,
  11087,
  18648,
  10,
  112,
  529,
  625,
  362,
  219,
  1046,
  5901,
  2568,
  31,
  2,
  135,
  3715,
  1369,
  755,
  262,
  270,
  1683,
  1740],
 [296,
  640,
  7,
  12,
  412,
  805,
  5,
  2,
  1196,
  10,
  860,
  8,
  59,
  704,
  13,
  25,
  5507,
  4179,
  27,
  39,
  1802,
  242,
  13,
  307,
  7,
  103],
 [13,
  149,
  72,
  31,
  74,
  868,
  50,
  14161,
  13,
  704,
  27,
  3,
  4380,
  63,
  166,
  169,
  4,
  43],
 [6,
  1402,
  1034,
  387,
  81,
  287,
  1384,
  17,
  7,
  72,
  38,
  1900,
  59,
  11088,
  112,
  4599,
  361],
 [26, 523, 402, 688, 58, 74, 23, 456, 8],
 [168,
  11,
  1035,
  469,
  972,
  172,
  2,
  154,
  4,
  87,
  53,
  13,
  179,
  6,
  75,
  676,
  315,
  765,
  1127,
  11,
  195,
  373,
  4,
  240,
  46,
  42,
  11,
  6,
  220,
  1083,
  1083,
  2315,
  839],
 [81,
  159,
  2278,
  17,
  72,
  31,
  109,
  4,
  55,
  16521,
  1684,
  11,
  7504,
  11,
  42,
  163,
  110,
  4180,
  93,
  7,
  51,
  705,
  2916,
  351,
  31,
  13,
  3,
  76,
  18,
  55,
  165,
  13,
  58,
  3,
  165,
  388,
  44,
  31,
  16522,
  11,
  13,
  4,
  165,
  66,
  13,
  204,
  1197,
  7504,
  17,
  9,
  6,
  508,
  54,
  243,
  4,
  408,
  36],
 [66, 3, 32, 35, 56, 95, 1216, 404, 27, 12, 184, 586, 876, 100, 1341, 81],
 [53, 3, 26, 510, 2, 7505, 2007, 7, 985, 2, 11089, 135, 546],
 [12,
  829,
  9,
  15,
  8701,
  903,
  2569,
  384,
  27,
  6935,
  5,
  1829,
  31,
  2627,
  27,
  12,
  10,
  15,
  590,
  4,
  41,
  94,
  20,
  567,
  388,
  13,
  58,
  1741,
  1084,
  10,
  2,
  503,
  17,
  70,
  128,
  6935,
  6,
  329],
 [347,
  42,
  8,
  16,
  6,
  2823,
  1198,
  66,
  9,
  4381,
  125,
  609,
  2375,
  1371,
  2376,
  8,
  16,
  167,
  551],
 [523, 1468, 7, 2, 89, 14, 75, 31, 6, 94, 869],
 [12,
  6936,
  68,
  86,
  16,
  6,
  651,
  7,
  794,
  3424,
  4600,
  11,
  1830,
  64,
  5,
  3425,
  738],
 [3, 35, 12, 526, 281, 52, 11, 2279, 5, 2, 352, 1424, 6937, 133],
 [114, 41, 20, 5, 41, 463, 93, 86, 9, 48, 107, 67, 111, 1493],
 [425,
  426,
  3,
  165,
  2,
  18,
  5166,
  233,
  945,
  870,
  17,
  44,
  76,
  18,
  5508,
  60,
  44,
  517],
 [187],
 [281,
  288,
  4,
  87,
  2,
  200,
  598,
  78,
  182,
  1469,
  394,
  5,
  378,
  3,
  210,
  32,
  62,
  223,
  50,
  4,
  25,
  87,
  66,
  2,
  877],
 [228, 3, 43, 4, 46, 413, 14, 2, 89, 5, 42, 89],
 [1342, 368, 92, 338, 1058, 2, 5902, 2234, 19, 18649],
 [66, 2, 502, 43, 551],
 [190, 68, 276, 2, 95, 713, 3311, 4, 240, 56],
 [77,
  1331,
  5903,
  2917,
  14162,
  18650,
  4860,
  5,
  4382,
  568,
  5167,
  19,
  11090,
  359,
  8702,
  832,
  121,
  359,
  4,
  482,
  62,
  11,
  220,
  34,
  11091,
  1341,
  11092],
 [519,
  1172,
  21,
  14163,
  1226,
  3208,
  269,
  4861,
  43,
  3716,
  332,
  10,
  15,
  108,
  2316,
  31,
  464,
  5,
  6,
  566,
  17,
  59,
  8,
  10,
  195,
  2154,
  327,
  7,
  29,
  3,
  32,
  74,
  14164,
  778,
  1277,
  2316,
  5,
  16523,
  143,
  113,
  14165],
 [54,
  154,
  15,
  79,
  122,
  34,
  174,
  309,
  322,
  249,
  9,
  730,
  420,
  2,
  20,
  46,
  184,
  1640,
  5,
  292,
  22,
  162,
  34,
  251,
  6,
  19,
  172,
  138,
  138,
  8703],
 [145, 13, 4015, 16524, 2570],
 [12, 9, 492, 15, 79, 1128, 14, 366, 571, 37, 1092, 8704, 310, 32],
 [55,
  700,
  3,
  104,
  104,
  35,
  6,
  89,
  67,
  6,
  895,
  6938,
  1685,
  153,
  844,
  2,
  671,
  5,
  3209,
  1164,
  76,
  18,
  353,
  23,
  22,
  136],
 [371, 171, 584, 7, 161, 1258, 2503, 160],
 [176,
  24,
  242,
  15,
  350,
  57,
  5,
  1227,
  7506,
  22,
  13,
  591,
  88,
  114,
  17,
  3,
  206,
  4,
  530,
  46,
  216,
  1187,
  34,
  324,
  11,
  8],
 [60, 224, 33, 2112, 258],
 [2918,
  2,
  8705,
  731,
  27,
  278,
  98,
  3007,
  191,
  2,
  4601,
  207,
  536,
  7,
  8706,
  31,
  536,
  7,
  118,
  51,
  276,
  12,
  88,
  539],
 [17,
  775,
  60,
  18651,
  2235,
  41,
  115,
  11093,
  552,
  315,
  5,
  1036,
  13,
  6,
  697,
  1741,
  11,
  41,
  903,
  706,
  9,
  2,
  327,
  8,
  16,
  746,
  36,
  163,
  42],
 [113, 223, 4, 25, 96, 11, 287, 37, 40, 19, 5509, 14166],
 [99,
  46,
  623,
  2571,
  220,
  2438,
  27,
  885,
  369,
  677,
  1686,
  4862,
  506,
  3863,
  1926,
  8,
  14167,
  32],
 [57, 226, 4, 418, 106, 156, 13, 29, 210, 87, 12, 114, 2, 20],
 [49,
  7,
  2,
  135,
  851,
  578,
  14168,
  70,
  8707,
  918,
  30,
  176,
  13,
  16525,
  2,
  513,
  5168,
  11,
  41,
  221,
  213,
  44],
 [117, 2155, 2008],
 [125, 68, 2, 90, 806, 533, 49, 3717, 6, 16, 512, 36, 2, 20],
 [3, 343, 60, 214, 33, 10],
 [1014,
  222,
  475,
  6934,
  5,
  1801,
  11087,
  4863,
  10,
  112,
  529,
  625,
  362,
  219,
  1046,
  5901,
  2236,
  3426,
  2,
  135,
  6395,
  1369,
  755,
  262,
  270,
  1683,
  1740],
 [29, 3, 32, 274, 467, 4, 9, 2, 529, 415, 192, 20, 4, 234, 36],
 [4, 12, 420, 8, 9, 49, 136],
 [68,
  9,
  2,
  951,
  20,
  20,
  10,
  1037,
  265,
  7,
  15,
  1712,
  603,
  5,
  39,
  140,
  50,
  4,
  802,
  98,
  114,
  8],
 [22, 17, 16, 252, 29, 2, 8708, 439, 3, 33, 3718],
 [47, 47, 50, 6, 1439, 416, 27, 74, 421, 18, 114, 2],
 [53,
  13,
  140,
  269,
  4,
  369,
  590,
  1453,
  203,
  7,
  5510,
  28,
  2317,
  4602,
  6396,
  9,
  255,
  57,
  12,
  9,
  28,
  1511,
  128,
  72,
  92,
  376,
  1259,
  10,
  112,
  2746,
  4,
  3427,
  1085,
  4,
  194,
  2,
  222,
  404,
  75,
  9,
  8709,
  186,
  5,
  8,
  30,
  254,
  495],
 [1742, 68, 30, 18, 3, 46, 97, 83, 969, 238, 560, 116],
 [53,
  3,
  861,
  66,
  136,
  9,
  29,
  2,
  2919,
  10,
  122,
  321,
  7,
  16,
  192,
  15,
  1663,
  31,
  2280],
 [76,
  18,
  576,
  68,
  44,
  3719,
  8,
  506,
  7,
  2156,
  14,
  4181,
  8,
  58,
  209,
  6,
  297,
  225],
 [689,
  2,
  3312,
  26,
  271,
  18,
  544,
  92,
  11,
  69,
  430,
  3,
  1278,
  3,
  25,
  104,
  22,
  232,
  361,
  252,
  3,
  32,
  35,
  11094,
  2,
  404,
  5,
  3,
  26,
  76,
  18,
  43,
  6,
  4182,
  3312,
  4,
  14169],
 [5,
  3,
  104,
  56,
  162,
  6397,
  3,
  137,
  4603,
  69,
  7,
  15,
  1571,
  4,
  6,
  604,
  3428,
  4383,
  61,
  256,
  6,
  5511,
  21,
  24],
 [29,
  1403,
  17,
  3,
  30,
  138,
  18,
  46,
  298,
  2,
  784,
  522,
  424,
  46,
  779,
  363,
  11,
  146,
  157,
  63,
  3,
  325,
  2,
  20,
  8,
  398,
  2,
  291,
  424,
  267,
  31,
  28,
  739,
  34,
  3429,
  12,
  63,
  3,
  85,
  73,
  501,
  418,
  146,
  157,
  353,
  11,
  45,
  272,
  45,
  3,
  30,
  569,
  27,
  3,
  483,
  23,
  2572,
  4,
  636,
  12,
  157,
  3111],
 [10,
  26,
  124,
  56,
  522,
  8,
  58,
  23,
  15,
  305,
  131,
  7,
  2,
  157,
  171,
  7,
  161,
  2047,
  3008,
  12,
  9,
  8,
  12,
  9,
  51,
  3,
  85,
  73,
  648,
  29,
  7,
  11,
  29,
  15,
  3313,
  11,
  12,
  157,
  256,
  6,
  1228,
  374,
  31,
  4183,
  14,
  12,
  20,
  10,
  332],
 [76, 18, 99, 709, 8710, 44, 26, 547, 129, 3, 25, 6939, 645],
 [3,
  388,
  439,
  6,
  4604,
  337,
  14170,
  123,
  21,
  26,
  2,
  1260,
  8711,
  125,
  14,
  4864,
  27,
  3,
  74,
  104,
  126,
  29,
  2,
  229,
  2628],
 [704, 626, 3, 82, 15],
 [90, 13],
 [3, 5904, 22, 345, 34, 256, 12],
 [58,
  13,
  74,
  88,
  287,
  2,
  244,
  20,
  41,
  1470,
  31,
  413,
  1015,
  43,
  10,
  17,
  1216,
  264,
  372,
  641,
  698,
  5,
  4015,
  5169,
  45,
  56],
 [3, 30, 87, 15, 4605, 163, 125, 163, 42],
 [353,
  181,
  110,
  476,
  5,
  1713,
  349,
  587,
  3720,
  74,
  42,
  25,
  20,
  229,
  10,
  1974,
  88,
  446,
  8,
  16,
  1199,
  5512,
  10,
  558,
  797,
  18652,
  1259,
  146,
  3721,
  1113,
  49,
  4865,
  10,
  2,
  8712,
  34,
  6,
  63],
 [3, 1303, 22, 107],
 [69,
  678,
  638,
  38,
  173,
  257,
  143,
  113,
  760,
  1803,
  388,
  57,
  1072,
  472,
  4,
  519,
  16526,
  526,
  96,
  96,
  96],
 [3, 871, 66, 15, 1664, 4606, 14, 2, 5905],
 [568, 568, 145, 7, 13, 11, 2],
 [397, 14171, 35, 12, 3430, 451, 9, 74, 412],
 [347, 51, 16, 21, 128, 338, 1470],
 [2439,
  65,
  1665,
  1242,
  279,
  4384,
  5906,
  89,
  992,
  1831,
  462,
  992,
  5906,
  34,
  2,
  374,
  7,
  6,
  2439,
  86,
  58,
  23,
  49,
  227],
 [175,
  7,
  1016,
  3,
  55,
  1229,
  12,
  54,
  817,
  26,
  82,
  6,
  91,
  968,
  10,
  2,
  257,
  1372,
  895,
  7507,
  21,
  2629],
 [26,
  766,
  766,
  14,
  6,
  959,
  431,
  10,
  6,
  4866,
  43,
  24,
  6,
  116,
  5,
  3,
  32,
  36,
  84,
  4184,
  7508,
  14,
  66,
  376,
  3,
  210,
  25,
  1200],
 [115,
  5513,
  70,
  518,
  886,
  952,
  7,
  2,
  1173,
  878,
  502,
  1286,
  860,
  588,
  511,
  929,
  8,
  8713],
 [347, 653, 5, 590, 7, 653, 31, 302, 508, 910],
 [3314,
  5907,
  1743,
  47,
  65,
  8714,
  1591,
  1641,
  11,
  5170,
  5908,
  19,
  1116,
  784,
  84],
 [22, 551, 130, 8715, 409],
 [830,
  5,
  168,
  11,
  2824,
  3112,
  14,
  2,
  405,
  17,
  8,
  16,
  73,
  124,
  6,
  63,
  218,
  3,
  4016,
  2318,
  938,
  4,
  2440,
  8716,
  5,
  82,
  1804,
  11,
  8,
  5,
  421,
  18,
  810,
  178,
  857,
  7,
  60,
  2,
  58,
  363,
  61,
  626,
  4,
  119,
  13,
  208,
  2157,
  17,
  718,
  5,
  452],
 [68, 271, 18, 2, 1047, 833, 588, 2573, 56, 4185, 2048],
 [122, 63, 1373, 11095, 14172, 271, 18, 209, 79, 27, 3, 104, 126, 1642],
 [66,
  2,
  90,
  210,
  13,
  28,
  35,
  97,
  83,
  142,
  74,
  46,
  12,
  20,
  60,
  3,
  32,
  3009,
  17,
  8,
  16,
  45,
  52,
  45,
  8,
  9],
 [51, 4017, 973, 90],
 [54, 133, 1243, 9, 55, 52, 5, 126],
 [68,
  28,
  263,
  92,
  609,
  153,
  4018,
  70,
  707,
  2920,
  4385,
  93,
  193,
  80,
  72,
  48,
  52,
  21,
  709,
  378,
  215,
  408,
  709,
  71,
  10,
  352,
  261,
  159,
  48,
  230,
  5171,
  453,
  1343,
  90,
  77,
  1141,
  2825,
  50,
  8,
  559],
 [562,
  188,
  3,
  520,
  4,
  176,
  325,
  124,
  70,
  723,
  13,
  5172,
  11,
  41,
  386,
  91,
  169,
  12,
  349,
  88,
  10,
  12,
  2049,
  3,
  25,
  73,
  218,
  256,
  6,
  4186,
  887,
  1188,
  10,
  15,
  118,
  311,
  4867,
  528,
  8717,
  3,
  25,
  1200,
  4187,
  27,
  13,
  30,
  3210,
  18,
  4607,
  198,
  38,
  2,
  14173,
  5514,
  6940,
  21,
  15,
  4867,
  565],
 [2,
  939,
  2685,
  724,
  1201,
  9,
  231,
  22,
  288,
  16527,
  5,
  22,
  624,
  164,
  136,
  68,
  44,
  74,
  76,
  823,
  18,
  408,
  8,
  10,
  14,
  6,
  3431,
  67,
  3211,
  94,
  3432],
 [228, 338, 3315, 114, 8, 37, 40, 19, 11096, 360],
 [52,
  479,
  29,
  8718,
  5,
  2921,
  6398,
  131,
  4,
  13,
  29,
  51,
  53,
  76,
  18,
  196,
  41,
  646,
  124,
  51,
  457,
  7,
  73],
 [47,
  47,
  59,
  1975,
  3010,
  111,
  416,
  407,
  779,
  14,
  6,
  18653,
  1618,
  5,
  2,
  5173,
  10,
  2,
  2922,
  779,
  7,
  3212,
  58,
  1665,
  2,
  290,
  4,
  87,
  53,
  2,
  2504,
  9,
  1643,
  4,
  2,
  2009],
 [624, 314, 4, 25, 10, 185],
 [918, 3, 13, 342, 29, 119, 603, 2, 83, 584, 34, 8719, 19, 3864],
 [41],
 [654, 340, 1304, 261, 2158, 14, 77],
 [114, 41, 337, 6399],
 [1092,
  96,
  3,
  619,
  12,
  10,
  1244,
  2159,
  5,
  56,
  6,
  1404,
  8720,
  7,
  6,
  3865,
  604,
  13,
  1550,
  4386,
  27,
  125,
  39,
  31,
  37,
  40,
  19,
  248,
  11097],
 [202],
 [1512, 1201, 9, 2, 54, 1639, 735],
 [1494, 24, 3, 26, 544, 610, 50, 66, 146, 20, 9, 1117, 689],
 [447,
  29,
  2,
  272,
  3866,
  7,
  415,
  192,
  780,
  429,
  24,
  22,
  792,
  11,
  121,
  20,
  365,
  144,
  11,
  2,
  379,
  844,
  182,
  278,
  3011,
  370,
  112,
  71,
  60,
  44,
  547,
  36,
  44,
  210,
  23,
  2826],
 [148,
  141,
  4,
  343,
  146,
  227,
  642,
  298,
  11,
  725,
  159,
  655,
  602,
  416,
  1226,
  1344,
  18654],
 [22, 278, 43, 14, 224, 121, 65, 29, 167, 6, 2827],
 [3012,
  9,
  534,
  2,
  4019,
  389,
  86,
  58,
  23,
  154,
  7,
  15,
  2686,
  538,
  6400,
  60,
  3,
  25,
  63,
  4,
  408,
  8,
  29,
  649],
 [117, 3, 25, 3867, 29, 455, 98, 14174, 29, 15, 1104, 11, 42, 163, 42, 35, 42],
 [241, 1832, 632, 4, 513, 147, 116, 372, 767],
 [4,
  25,
  3316,
  7,
  224,
  29,
  112,
  226,
  100,
  217,
  349,
  3,
  26,
  1261,
  5,
  1129,
  34,
  7,
  15,
  1073,
  3316,
  3,
  32,
  422,
  42],
 [39, 140, 256, 126, 10, 69, 1976, 143, 113, 11098, 11099],
 [172,
  2,
  122,
  99,
  736,
  4020,
  832,
  14,
  5909,
  672,
  5,
  97,
  2113,
  7,
  11100,
  16,
  162,
  360,
  8721,
  128,
  162,
  18655,
  31,
  739,
  11,
  832,
  18656,
  19,
  3722,
  3013,
  5174],
 [3433],
 [168,
  11,
  1592,
  7509,
  14,
  40,
  266,
  36,
  360,
  15,
  77,
  588,
  4,
  87,
  51,
  3,
  32,
  61,
  4],
 [51,
  6,
  2160,
  257,
  6,
  1440,
  1243,
  34,
  11101,
  5,
  265,
  303,
  761,
  54,
  72,
  8,
  33,
  91,
  1666,
  11102,
  39,
  4608,
  2,
  1927,
  4,
  72,
  80,
  216,
  1187,
  200,
  2,
  160,
  160,
  313,
  58,
  23,
  1245,
  313,
  904,
  2,
  54,
  1572,
  724],
 [65, 170, 158, 11, 62, 130, 6, 328, 164, 1031],
 [133,
  16,
  3723,
  803,
  4868,
  592,
  460,
  21,
  3566,
  16,
  169,
  5515,
  270,
  454,
  8722,
  2687,
  3724,
  18,
  199,
  18657,
  8723],
 [76, 18, 120, 323, 57, 225, 117, 5, 71, 1425],
 [75,
  9,
  182,
  56,
  261,
  163,
  42,
  67,
  103,
  679,
  785,
  354,
  261,
  11103,
  342,
  2237,
  15,
  1619,
  1032],
 [133,
  160,
  2074,
  23,
  11104,
  1714,
  11105,
  217,
  234,
  172,
  45,
  3,
  5910,
  1029,
  6,
  255,
  490,
  993,
  48,
  12,
  160],
 [30, 18, 144, 4, 92],
 [2, 1048, 5516, 9, 100, 2923, 29],
 [228, 227, 132, 228],
 [3, 148, 719, 235, 14, 118, 565, 1093],
 [16528,
  30,
  13,
  974,
  266,
  1165,
  7,
  8724,
  7,
  16529,
  616,
  44,
  31,
  28,
  3014,
  1165,
  67,
  69,
  1744,
  326,
  81,
  8,
  16,
  41,
  1744],
 [2,
  1440,
  2688,
  11,
  18658,
  26,
  998,
  56,
  877,
  251,
  154,
  2161,
  12,
  2574,
  11106,
  26,
  998,
  8,
  14,
  15,
  77,
  53,
  13,
  141,
  2,
  568,
  67,
  13,
  99,
  293,
  245,
  747,
  33,
  2010,
  139,
  2010,
  4,
  568,
  1593,
  294,
  172,
  19,
  310,
  8725],
 [97, 83, 142, 10, 3725, 2377, 37, 40, 19, 14175],
 [13, 31, 6, 784, 656, 1094, 7, 1031, 71, 2114, 823, 18, 13],
 [145, 65, 75, 11, 12, 960, 145],
 [9,
  86,
  1687,
  4,
  114,
  2,
  736,
  3015,
  10,
  1901,
  548,
  772,
  650,
  186,
  6,
  5175,
  1865,
  109,
  183,
  6,
  7510,
  8,
  16,
  55,
  11107,
  3,
  576,
  8726,
  1573,
  27,
  2,
  18659,
  461,
  4,
  5911,
  14,
  178,
  18660,
  178,
  580,
  9,
  2505,
  61,
  14,
  28,
  11108],
 [129,
  8,
  33,
  126,
  7511,
  273,
  519,
  11,
  2,
  131,
  1405,
  36,
  4,
  15,
  1642,
  197,
  11,
  1666,
  21,
  24,
  129,
  92,
  259,
  24,
  6,
  642,
  143,
  113,
  4021,
  143,
  113,
  4021,
  143,
  113,
  4021,
  3434,
  11109,
  70,
  18661],
 [28, 12, 63],
 [2630, 24, 166, 146, 63, 3, 87, 8, 10, 20],
 [53, 2, 1332, 9, 74, 14176, 3, 867, 13, 2575],
 [224,
  267,
  31,
  55,
  136,
  129,
  394,
  73,
  256,
  1217,
  7,
  1770,
  1315,
  930,
  536,
  5,
  1594,
  536,
  3,
  421,
  18,
  540,
  377,
  998,
  38,
  437,
  67,
  224,
  27,
  53,
  13,
  25,
  460,
  21,
  8,
  959,
  334,
  109,
  4,
  1833,
  20,
  400,
  5,
  334,
  123],
 [117,
  11110,
  367,
  113,
  1218,
  755,
  45,
  5912,
  2747,
  7512,
  11111,
  14,
  4609,
  2,
  19,
  1374,
  217,
  2,
  117,
  940,
  2011,
  4,
  13,
  4386,
  363,
  41,
  1771,
  287,
  36,
  4,
  117,
  283,
  14,
  2747,
  2,
  5912],
 [779, 147, 70, 1745, 4869, 1595, 31, 196, 54, 1049, 1928, 1535, 21, 220],
 [477],
 [81,
  159,
  2115,
  17,
  42,
  17,
  2,
  4180,
  9,
  124,
  72,
  31,
  18662,
  1684,
  11,
  7504,
  93,
  705,
  351,
  531,
  3,
  76,
  18,
  165,
  13,
  58,
  3,
  165,
  44,
  140,
  723,
  13,
  6941,
  17,
  165,
  13,
  204,
  1197,
  7504,
  17,
  16,
  6,
  508,
  243],
 [888,
  3,
  32,
  16530,
  2,
  262,
  11,
  12,
  95,
  363,
  3,
  32,

In [18]:
max_len =  int(np.percentile([len(x) for x in X_train_seq], 95))

In [19]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X_train_pad = pad_sequences(X_train_seq, maxlen=max_len, padding='post')
X_val_pad   = pad_sequences(X_val_seq,   maxlen=max_len, padding='post')  # ← جديد
X_test_pad  = pad_sequences(X_test_seq,  maxlen=max_len, padding='post')

In [20]:
X_train_pad

array([[2913,  215,   59, ...,    0,    0,    0],
       [   2,  122,  321, ...,    0,    0,    0],
       [  52,  479,   52, ...,    0,    0,    0],
       ...,
       [ 211, 1754,    4, ...,    0,    0,    0],
       [  19,   76,   18, ...,    0,    0,    0],
       [  62,  865,   11, ...,    0,    0,    0]],
      shape=(49353, 48), dtype=int32)

In [21]:
vocab_size = len(tokenizer.word_index) + 1

In [22]:
vocab_size

24099

In [23]:
Y.value_counts()

Labels
0    22542
2    20832
1    18318
Name: count, dtype: int64

In [36]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, SimpleRNN
model_LSTM = Sequential([
    Embedding(input_dim=vocab_size, output_dim=128, mask_zero=True),
    LSTM(128, return_sequences=True, recurrent_dropout=0.1),
    LSTM(256, return_sequences=True, recurrent_dropout=0.1),
    LSTM(128, return_sequences=True, recurrent_dropout=0.1),
    LSTM(64, recurrent_dropout=0.1 ,dropout=0.2),
    Dense(64, activation="relu"),
    Dropout(0.4),
    Dense(64, activation="relu"),
    Dropout(0.4),
    Dense(3, activation="softmax")
])

model_RNN = Sequential([
    Embedding(input_dim=vocab_size, output_dim=128, mask_zero=True),
    SimpleRNN(128, return_sequences=True),
    SimpleRNN(256, return_sequences=True),
    SimpleRNN(128, return_sequences=True),
    Dropout(0.2),
    SimpleRNN(64),
    Dropout(0.2),
    Dense(64, activation="relu"),
    Dropout(0.2),
    Dense(64, activation="relu"),
    Dropout(0.3),
    Dense(3, activation="softmax")
])

In [40]:
from tensorflow.keras.optimizers import Adam
model_LSTM.compile(optimizer=Adam(learning_rate=0.001),loss="sparse_categorical_crossentropy",metrics=["accuracy"])
model_LSTM.summary()

model_RNN.compile(optimizer=Adam(learning_rate=0.001),loss="sparse_categorical_crossentropy",metrics=["accuracy"])
model_RNN.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_4 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_5 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_6 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_7 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_10 (Dropout)            │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_11 (Dropout)            │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [38]:
ytrain.value_counts()

Labels
0    18033
2    16666
1    14654
Name: count, dtype: int64

In [39]:
class_weights

{np.int64(0): np.float64(0.9122719458770032),
 np.int64(1): np.float64(1.1226286338201175),
 np.int64(2): np.float64(0.9870994839793592)}

In [28]:
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import *
early_stop = EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True)

history_LSTM = model_LSTM.fit(
    X_train_pad,
    ytrain,
    epochs=6,
    batch_size=128,
    validation_data=(X_val_pad,yval),
    class_weight=class_weights,
    callbacks=[early_stop]

    )

history_RNN = model_RNN.fit(
    X_train_pad,
    ytrain,
    epochs=7,
    batch_size=128,
    validation_data=(X_val_pad,yval),
    class_weight=class_weights,
    callbacks=[early_stop]

    )

Epoch 1/6
386/386 ━━━━━━━━━━━━━━━━━━━━ 151s 368ms/step - accuracy: 0.6527 - loss: 0.7870 - val_accuracy: 0.7953 - val_loss: 0.5304
Epoch 2/6
386/386 ━━━━━━━━━━━━━━━━━━━━ 139s 359ms/step - accuracy: 0.8629 - loss: 0.3820 - val_accuracy: 0.8640 - val_loss: 0.3706
Epoch 3/6
386/386 ━━━━━━━━━━━━━━━━━━━━ 166s 430ms/step - accuracy: 0.9095 - loss: 0.2449 - val_accuracy: 0.8906 - val_loss: 0.2984
Epoch 4/6
386/386 ━━━━━━━━━━━━━━━━━━━━ 186s 482ms/step - accuracy: 0.9304 - loss: 0.1838 - val_accuracy: 0.8896 - val_loss: 0.3135
Epoch 5/6
386/386 ━━━━━━━━━━━━━━━━━━━━ 207s 535ms/step - accuracy: 0.9388 - loss: 0.1540 - val_accuracy: 0.9005 - val_loss: 0.2995
Epoch 6/6
386/386 ━━━━━━━━━━━━━━━━━━━━ 216s 559ms/step - accuracy: 0.9450 - loss: 0.1342 - val_accuracy: 0.8992 - val_loss: 0.3240
Epoch 1/7
386/386 ━━━━━━━━━━━━━━━━━━━━ 52s 121ms/step - accuracy: 0.3544 - loss: 1.0988 - val_accuracy: 0.3902 - val_loss: 1.0823
Epoch 2/7
386/386 ━━━━━━━━━━━━━━━━━━━━ 42s 110ms/step - accuracy: 0.3890 - loss: 1.0633 - val_accuracy: 0.3850 - val_loss: 1.0823
Epoch 3/7
386/386 ━━━━━━━━━━━━━━━━━━━━ 39s 101ms/step - accuracy: 0.4964 - loss: 0.9556 - val_accuracy: 0.6029 - val_loss: 0.7927
Epoch 4/7
386/386 ━━━━━━━━━━━━━━━━━━━━ 38s 99ms/step - accuracy: 0.6033 - loss: 0.7257 - val_accuracy: 0.6215 - val_loss: 0.7125
Epoch 5/7
386/386 ━━━━━━━━━━━━━━━━━━━━ 40s 104ms/step - accuracy: 0.6230 - loss: 0.6417 - val_accuracy: 0.5844 - val_loss: 0.6834
Epoch 6/7
386/386 ━━━━━━━━━━━━━━━━━━━━ 40s 103ms/step - accuracy: 0.6394 - loss: 0.6030 - val_accuracy: 0.5956 - val_loss: 0.6636

In [41]:
history_RNN = model_RNN.fit(
    X_train_pad,
    ytrain,
    epochs=15,
    batch_size=128,
    validation_data=(X_val_pad,yval),
    class_weight=class_weights,
    callbacks=[early_stop]

    )

Epoch 1/15
386/386 ━━━━━━━━━━━━━━━━━━━━ 41s 95ms/step - accuracy: 0.3743 - loss: 1.0909 - val_accuracy: 0.3638 - val_loss: 1.0696
Epoch 2/15
386/386 ━━━━━━━━━━━━━━━━━━━━ 38s 98ms/step - accuracy: 0.4005 - loss: 1.0648 - val_accuracy: 0.3989 - val_loss: 1.0754
Epoch 3/15
386/386 ━━━━━━━━━━━━━━━━━━━━ 37s 95ms/step - accuracy: 0.4045 - loss: 1.0608 - val_accuracy: 0.4135 - val_loss: 1.0427
Epoch 4/15
386/386 ━━━━━━━━━━━━━━━━━━━━ 38s 99ms/step - accuracy: 0.5977 - loss: 0.8578 - val_accuracy: 0.7380 - val_loss: 0.6625
Epoch 5/15
386/386 ━━━━━━━━━━━━━━━━━━━━ 38s 99ms/step - accuracy: 0.8264 - loss: 0.4872 - val_accuracy: 0.8489 - val_loss: 0.4264
Epoch 6/15
386/386 ━━━━━━━━━━━━━━━━━━━━ 37s 96ms/step - accuracy: 0.8924 - loss: 0.3173 - val_accuracy: 0.8690 - val_loss: 0.3773

In [44]:
model_RNN.evaluate(X_test_pad, ytest)

193/193 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.3703 - loss: 1.0701

[1.0700873136520386, 0.37034034729003906]

In [45]:
model_LSTM.evaluate(X_test_pad, ytest)

193/193 ━━━━━━━━━━━━━━━━━━━━ 8s 33ms/step - accuracy: 0.3130 - loss: 1.0986

[1.0986385345458984, 0.3129659593105316]

In [46]:
import re
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#", "", text)
    text = re.sub(r"[^a-zA-Z ]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def predict(text):
    seq = tokenizer.texts_to_sequences([clean_text(text)])
    seq = pad_sequences(seq, maxlen=max_len)
    
    pred = model_LSTM.predict(seq)
    labels = ['positive', 'negative', 'neutral']
    return labels[pred.argmax()]

predict("I love this phone")

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step

'positive'

In [47]:
model_LSTM.save('model_LSTM.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [48]:
model_RNN.save('model_RNN.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [49]:
from tensorflow.keras.models import load_model
model=load_model("model_LSTM.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [61]:
import re
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
tokenizer = Tokenizer()
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#", "", text)
    text = re.sub(r"[^a-zA-Z ]", " ", text)
    text = re.sub(r"\s+", " ", text).strip() 
    return text

def predict(text):
    seq = tokenizer.texts_to_sequences([clean_text(text)])
    seq = pad_sequences(seq, maxlen=max_len)
    
    pred = model_RNN.predict(seq)
    labels = ['positive', 'negative', 'neutral']
    return labels[pred.argmax()] , pred
predict("""I really love this new update, the gameplay feels smooth and fun. @GameDev please keep improving the experience,1,i really love this new update the gameplay feels smooth and fun please keep improving the experience,[],['GameDev']""")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 344ms/step

('positive', array([[0.34375045, 0.33406103, 0.32218856]], dtype=float32))

In [62]:
predict("""I am so happy with the service, everything works perfectly and fast,1,i am so happy with the service everything works perfectly and fast,[],[]""")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

('positive', array([[0.34375045, 0.33406103, 0.32218856]], dtype=float32))

In [63]:
predict("""This is the worst experience I have ever had, nothing works and I am very frustrated,1,this is the worst experience i have ever had nothing works and i am very frustrated,[],[]""")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

('positive', array([[0.34375045, 0.33406103, 0.32218856]], dtype=float32))